### ISSUE TITLE
Regarding the recent breach of your Organization

### ISSUE THREAD

**Issue by ghost** [FudanSELab/doc-generate#4]
Hello,

Someone had gained unauthorized access to your organization owner's github account earlier this year.

The person/people who gained the access did **NOT** download any files. All of your data is safe and will **NOT** be disclosed under any circumastances.

In the words of @TerryMXJ "The greatest victory is the victory over yourself." and, after struggling to come to terms with what they have done, the person/people who did this have come to recognize what they have done is very wrong. They promise to never engage in such activites again.

The person/people who gained access are **extremley sorry** and regretful for what they have done. They hope you can accept their apoligies for the trouble they caused.

Stay safe. Good luck with your future work.

@indispensible @lanxingdouble Please feel free to close / delete this issue.

**Comment by TerryMXJ** [comment]
No issue.
